project:
  type: website

website:
  title: "tidytuesday"
  navbar:
    left:
      - href: index.qmd
        text: Overview
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
