project:
  type: website

website:
  title: "Philipp's Tidy Tuesday Posts"
  description: "Visualizations of fascinating datasets using the tidytuesday challenges as inspiration. Detailed blog posts explain the creation process whenever possible."
  navbar:
    left:
      - href: index.qmd
        text: Overview
    right:
      - icon: github
        href: https://github.com/pkollenda/tidytuesday.git
        aria-label: GitHub
  open-graph: true
  twitter-card: 
    site: "@sitehandle"
    creator: "@philippkollenda"
    
format:
  html:
    theme: solar
    css: styles.css
    toc: true
